project:
  type: website
  output-dir: _site
  preview:
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "ホットピクセルの一生"
  site-url: "https://goldkiss2010-ai.github.io/hot-pixel-journey-public/"
  navbar: false

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: true
    code-copy: true
    fig-align: center
    theme: cosmo

execute:
  echo: false
  warning: false
  message: false
  freeze: false

bibliography: references.bib
lang: ja
